### PR TITLE
Venezuela (National Assembly): refresh data

### PR DESCRIPTION
**Pull request by everypoliticianbot**
Automated data refresh for Venezuela - National Assembly

#### Output

```
Add memberships from sources/morph/official2011.csv
Add memberships from sources/morph/official2016.csv
Merging with sources/morph/wikidata.csv
* 4 of 61 unmatched
	{:id=>"Q25412674", :name=>"José Guerra"}
	{:id=>"Q16145525", :name=>"Alfredo Ramos"}
	{:id=>"Q9070660", :name=>"Roque Valero de Maduro"}
	{:id=>"Q5948223", :name=>"Juan Carlos Caldera"}
Adding GenderBalance results from sources/gender-balance/results.csv
  ⚥ data for 62; 62 added

Creating 2 term files

Top identifiers:
  57 x wikidata
  6 x viaf
  5 x freebase
  3 x sudoc
  2 x bnf

Creating names.csv
Creating unstable/positions.csv
Persons matched to Wikidata: 57 ✓ | 222 ✘
  No wikidata: GUÉDEZ DE RIERA MARIBEL (7ffb2a71-b841-4696-bcda-ad5f4a842afb)
  No wikidata: PERÉZ GONZÁLEZ MARÍA TERESA (a6ed4a1d-2f8a-44d2-8b20-cdf91f7fea4c)
  No wikidata: RODRIGUEZ AZOCAR RAFAEL (4f964e02-cba2-4439-b61a-e47a4def6962)
  No wikidata: ÁNGEL EDUARDO GÓMEZ SIGALA (0db84297-6f5b-4bb6-87cc-dcb84142daa6)
  No wikidata: GUILLERMO ANTONIO PALACIOS (0d29064b-4ed3-4427-8e7d-58eb1be6e3ff)
  No wikidata: SUÁREZ LUCENA BOLIVIA MILAGRO (4d12b0f1-b93b-42c1-9af4-66e2fa58e20b)
  No wikidata: HERNÁN CLARET ALEMÁN PÉREZ (4c10d33a-b9ea-4c57-ba6b-0f41d0d02ce0)
  No wikidata: CLARK BOSCÁN VICTOR JOSÉ (b269d897-786c-4cb1-8bc6-39cc11915ea8)
  No wikidata: RODRIGUEZ FRANCO NOSLIW ANDREINA (d195d571-119a-4ba6-8176-c4850e3e8633)
  No wikidata: SILVA ALACAYO LUIS ALBERTO (45b8fb6b-1f57-4723-b93f-7a6fadd3835c)
Parties matched to Wikidata: 13 ✓ | 2 ✘
  No wikidata: APC (20)
  No wikidata: GE (11)

```

### CODE REVIEW

**Comment by tmtmtmtm** [comment]
Reported as https://github.com/everypolitician/everypolitician-data/issues/15404

**Comment by ondenman** [comment]
Reopening to fix data import issue.

**Comment by tmtmtmtm** [comment]
@ondenman This is the wrong way to fix this, I'm afraid. We'd only archive people off like that if their Wikipedia page were to completely vanish for some reason. Here the page still exists, so this way means we'll never get any updates again when that page changes.  Instead you need to find out why the scraper is no longer getting this person, and add them back.

**Comment by tmtmtmtm** [comment]
Fixed in https://github.com/everypolitician-scrapers/venezuela-asamblea-wikidata/pull/1

**Pull request closed without merging**
