### PR TITLE
Twitter list El Salvador

### PR DESCRIPTION
**Pull request by ondenman**
Add twitter data from https://twitter.com/AsambleaSV/lists/diputadas-y-diputados
via scraper at https://github.com/everypolitician-scrapers/twitter-list-el-salvador

### CODE REVIEW

**Comment by tmtmtmtm** [comment]
@ondenman https://github.com/everypolitician/everypolitician-data/pull/14347/commits/b9482d6d0bdb101e4a17bdbffe84a25533dccd15 has _removed_ lots of files, rather than re-generating them…

**Comment by tmtmtmtm** [comment]
@ondenman I think you're going to need to add some explanations here for which account(s) you're skipping when people have more than one. When I tried reconciling this one I ended up with quite different results from you.

For example, Cristina López has three twitter accounts:
* https://twitter.com/CLopezDiputada
* https://twitter.com/DiputadaCLopez
* https://twitter.com/CLopezPCN

The first two seem like they're both active accounts in her role as Deputy — the third is from when she was running as a candidate. So I'd include the first two and omit the third. But you seem to have chosen the opposite?

**Comment by ondenman** [comment]
# Karina Sosa
https://twitter.com/KarinaSosa_2 -- current account
https://twitter.com/KarinaISosa -- recent account

# Christina Lopez
https://twitter.com/CLopezPCN -- campaign account, skipped
https://twitter.com/CLopezDiputada -- current
https://twitter.com/DiputadaCLopez -- current

# Mauricio Linares
https://twitter.com/LinaresUsulutan -- current
https://twitter.com/ingmlinaress -- current

# Ricardo Godoy
https://twitter.com/ricar_godoy -- current
https://twitter.com/GodoyDiputado -- old campaign account, skipped

# Vilma Carolina Rodríguez Dávila 
https://twitter.com/carodavila1 -- current

# Carolina Rodriguez
https://twitter.com/caro_davila87 -- removed, personal

**Comment by tmtmtmtm** [comment]
@ondenman I'm not sure I follow your reasoning with the two Carolina Rodriguez accounts (I'm pretty sure they're the same person). Why are skipping the caro_davila87 one as personal? It looks to me as if that's her primary account as a Deputy… Maybe @octopusinvitro can help us unravel what each of these is for?

**Comment by octopusinvitro** [comment]
@tmtmtmtm I told him to choose [@carodavila1](https://twitter.com/carodavila1) Since the description says
"_Diputada al servicio de la ciudadania del departamento de Ahuachapan_"
and its full of job pictures.

And the other one is just her with her husband and son.

**Comment by tmtmtmtm** [comment]
@ondenman — @octopusinvitro and I discussed this in person, and we're now convinced that `@caro_davila87` is the correct one. The comments above seem to be have been based on looking at the wrong page.

**Comment by ondenman** [comment]
@tmtmtmtm fixed https://github.com/everypolitician/everypolitician-data/pull/14347/commits/172f692645be8ba59ba2581ddbc808e0f048e945

**Comment by tmtmtmtm** [comment]
I've cleaned up the history of this and rebased.

**Pull request merged**
