### PR TITLE
New Caledonia (Congress): refresh data

### PR DESCRIPTION
**Pull request by everypoliticianbot**
Automated data refresh for New Caledonia - Congress

#### Output

```
⤈ No ORDER BY for sources/morph/members.csv
Add memberships from sources/morph/members.csv
Merging with sources/morph/wikidata.csv
* 49 of 70 unmatched
	{:id=>"Q3159243", :name=>"Jacques Lafleur"}
	{:id=>"Q3384183", :name=>"Pierre Bretegnier"}
	{:id=>"Q3524521", :name=>"Thierry Song"}
	{:id=>"Q3590961", :name=>"Éric Babin"}
	{:id=>"Q3484356", :name=>"Simon Loueckhote"}
	{:id=>"Q544880", :name=>"Maurice Ponga"}
	{:id=>"Q2960011", :name=>"Charles Pidjot"}
	{:id=>"Q3035085", :name=>"Dominique Daly"}
	{:id=>"Q3292177", :name=>"Marie-Noëlle Thémereau"}
	{:id=>"Q2851626", :name=>"Annie Beustes"}
Adding GenderBalance results from sources/gender-balance/results.csv
  Unclear gender vote pattern: {:uuid=>"aebc7d1e-45a2-49ab-b6c9-1cd9089eb61b", :female=>5, :male=>2, :other=>0, :skip=>0, :total=>7}
  ⚥ data for 29; 29 added

Creating 1 term file

Top identifiers:
  21 x wikidata
  4 x sudoc
  4 x viaf
  3 x bnf
  3 x freebase

Creating names.csv
Creating unstable/positions.csv
  Unknown position (x5): Q382617 maire — e.g. Q3014101
Persons matched to Wikidata: 21 ✓ | 35 ✘
  No wikidata: Ithupane Tieoue (04058462-8af3-4e6d-bf71-4ae476a9183d)
  No wikidata: Basile Citre (f3879457-f317-4793-a3f4-49c2115749a2)
  No wikidata: Corinne Voisin (3684f371-5a77-4d9a-99e5-d79866e385e8)
  No wikidata: Joseph Goromido (5a09db2a-592b-49c8-9b6b-10a787bee0c7)
  No wikidata: Nina Lucas-Julie (0c54dfa9-d5fc-4068-89c8-1b26e4151b49)
  No wikidata: Philippe Blaise (bf4c5ae5-7795-4b3d-a13c-038ae0237e1a)
  No wikidata: Gil Brial (7cca05ff-d5d7-431c-97f3-e27b0380b899)
  No wikidata: Francis Euriboa (3c854926-376f-4bbd-b2c8-a0565e1703d5)
  No wikidata: Henriette Falelavaki (0e659146-a0ec-4f3a-8d5d-db433af45fa2)
  No wikidata: Prisca Holero (6c35cc53-7144-470b-884c-7012d67820c6)
Parties matched to Wikidata: 5 ✓ 

```

### CODE REVIEW

**Comment by tmtmtmtm** [comment]
reported as https://github.com/everypolitician/everypolitician-data/issues/14910

**Comment by tmtmtmtm** [comment]
reported as https://github.com/everypolitician/everypolitician-data/issues/14910

**Comment by ondenman** [comment]
Reopening. Placing Martine Lagneau in manual/members.csv

**Comment by tmtmtmtm** [comment]
superseded by https://github.com/everypolitician/everypolitician-data/pull/15067

**Pull request closed without merging**
