### PR TITLE
Sweden (Riksdag): refresh data

### PR DESCRIPTION
**Pull request by everypoliticianbot**
Automated data refresh for Sweden - Riksdag

#### Output

```
Wikidata renamings:
	Q18238725, Q23042185
Add memberships from sources/morph/data.csv
Merging with sources/morph/wikidata.csv
Data Mismatches
  ☁ Mismatch in death_date for 23c07bbc-ad79-4976-b617-19da6d263664 (2016-09-13) vs 2016-09-11 (for Q6053983)
* 8 of 1252 unmatched
	{:id=>"Q9393603", :name=>"Åsa Eriksson"}
	{:id=>"Q4969913", :name=>"Elise Norberg"}
	{:id=>"Q5854875", :name=>"Lars Engqvist"}
	{:id=>"Q4934552", :name=>"Rigmor Ahlstedt"}
	{:id=>"Q6193316", :name=>"Håkan Strömberg"}
	{:id=>"Q4969593", :name=>"Christin Nilsson"}
	{:id=>"Q6240649", :name=>"Jon Peter Wieselgren"}
	{:id=>"Q4971163", :name=>"Karin Olsson"}
Merging with sources/morph/twitter.csv
Data Mismatches
* 7 of 294 unmatched
	{:id=>"2371881938"}
	{:id=>"608202622"}
	{:id=>"2479331902"}
	{:id=>"2315230584"}
	{:id=>"2490524403"}
	{:id=>"2297877809"}
	{:id=>"18772213"}
Adding GenderBalance results from sources/gender-balance/results.csv
  ⚥ data for 953; 0 added


Top identifiers:
  1625 x riksdagen
  1244 x wikidata
  221 x viaf
  166 x freebase
  55 x isni

Creating names.csv
Persons matched to Wikidata: 1244 ✓ | 381 ✘
  No wikidata: Erik Edin (73be4ba9-f3ec-4bb2-a8be-0278f10ca880)
  No wikidata: Lars Norberg (a942083f-af94-426a-b7f0-f6bde88f5334)
  No wikidata: Rene Francis (5ca0ffb2-f29e-4e0f-87fc-901e172a6a53)
  No wikidata: Tomas Agenberg (d7e0e852-d578-4da5-ad6b-906e74f7de66)
  No wikidata: Jan Hyttring (29e21050-ef41-4bc5-9d24-a2cea6d1b5bf)
  No wikidata: Sven-Olof Nordlund (7f3b93f0-be16-41e0-9030-61eaf84fc974)
  No wikidata: Petra Gardos (fdec19e9-191a-48e6-b9a6-09bee11a003e)
  No wikidata: Tomas Avenborg (25e5b691-e473-4244-8137-ef5331a49519)
  No wikidata: Torgny Johansson (9130228e-2520-4d99-a943-ca744d3f1fad)
  No wikidata: John Johnsson (6de34f0d-ce8e-4ee5-8c6b-837515f158ba)
Parties matched to Wikidata: 9 ✓ | 1 ✘
  No wikidata: Independent (IND)
Areas matched to Wikidata: 0 ✓ | 29 ✘

```

### CODE REVIEW

**Comment by ondenman** [comment]
Issue: https://github.com/everypolitician/everypolitician-data/issues/25278

**Comment by ondenman** [comment]
Fixes: #25278

**Comment by ondenman** [comment]
@tmtmtmtm 👀 I've now paired both wikidata IDs

**Comment by tmtmtmtm** [comment]
@ondenman looks like only one of the two new Wikidata IDs actually gets reflected in the data, though…

**Pull request merged**
