### PR TITLE
Benin (Assemblée Nationale): refresh data

### PR DESCRIPTION
**Pull request by everypoliticianbot**
Automated data refresh for Benin - Assemblée Nationale
#### Output

```
⤈ No ORDER BY for sources/morph/data.csv
⤈ No ORDER BY for sources/morph/terms.csv
Add memberships from sources/morph/data.csv
michel_abimbola -> 203eede5-0951-4437-92f5-1b16d7f2f15c
jeremie_adomahou -> 9f1ea2f3-9332-40f9-9b61-0a6e6097d3a7
tidjani_affoobo -> 82650846-9484-47fb-aa0a-fd3e3e676bd1
alexis_agbelessessi -> c38b7e09-c395-4e9c-8777-254076623b88
justin_agbodjete -> 5d5fa55b-e0a6-41a4-9848-892a59123eae
edmond_agoua -> 3f438027-eeb0-49e1-8a76-8430ceac17dc
badiroudin_aguemon -> 5c7111b5-0455-4dfc-9e93-08c63ab68729
marcellin_ahonoukoun -> fcb6dd44-50e0-412c-8464-9ad87b16c161
leon_ahossi -> 433e1de4-0301-4d79-b129-21f47365f3c2
augustin_ahouanvoebla -> 82197d3a-4fd4-404a-8aad-22404dc5690a
natonde_ake -> 7b2f44a1-3dcd-454b-8355-d145f3c5416e
noel_akissoe -> 0ad0a66d-19c8-412d-83ff-53f80452b2b5
raphael_akotegnon -> 4309e700-3a2f-497f-9af1-5ce73d419afb
bruno_amoussou -> 1c9ef729-ff07-47fe-8ff7-70ca79a25f2d
nourenou_atchade -> 388d9785-aff9-4d45-953a-a1a0604ce2ff
candide_azannai -> ec482fbe-3e44-4b1f-9be6-541050d84337
adam_bagoudou -> b29fa8a7-eb05-4fa1-aecc-57560ee847a9
rene_bagoudou -> 0b4cb07f-069b-49b0-a0ac-91042326cec1
chabi_bahguera -> 5bf32f2b-72a7-4eb2-9c14-22f66c831d4d
idrissou_bako -> a0ae276d-1ba0-4d1a-943a-435f9685d452
nassirou_bakoarifari -> 96943a60-b40e-49ee-b79a-1925a3aeb9f9
joseph_djogbenou -> b39247bd-f557-4b93-b37f-b9220891f4a1
rachidi_gbadamassi -> b7292b17-8ae7-42f0-a5dc-ef5a509d7158
robert_gbian -> d0241652-0740-4ecf-a06d-e8196f728089
octave_houdegbe -> 13fbe207-e7c3-4479-8994-d09674e8ac6d
eric_houndete -> 0c6d05f5-98cd-4872-a23c-c2a56b316084
valentin_houde -> d79429f4-2c1e-4ace-8447-c7982433eb0c
adrien_houngbedji -> 23df6b0e-ed40-484c-bfd1-09428fe76790
kolawole_idji -> 7f0a4921-66ee-400e-b6a5-09b5381ef9ef
barthelemy_kassa -> 9b7e50ac-1736-4ff1-8a9d-58d917e7ac23
mathurin_nago -> 645e4de6-c935-490c-a4c8-6ee00c9aa6d0
andre_okounlola -> 95c75503-385f-42ba-ba56-917953077597
claudine_prudencio -> 967b5309-373c-4ae2-a196-067ad8c1f99a
sofiatou_schanou -> e9fd0728-5264-447f-a6dd-f8b521e44f9a
honorine_vieyra -> a92aa223-9d7b-4de4-bd1f-b6d963a4b9a0
Adding GenderBalance results from sources/gender-balance/results.csv
  ⚥ data for 1; 1 added

Creating names.csv
Persons matched to Wikidata: 0 ✓ | 118 ✘
Parties matched to Wikidata: 2 ✓ | 15 ✘
  No wikidata: Refondation et Progrès (refondation_et_progrès)
  No wikidata: UMPP Unité – Solidarité – Progrès (umpp_unité_solidarité_progrès)
  No wikidata: Refondation, Paix et Développement (refondation_paix_et_développement)
  No wikidata: Union Paix et Démocratie (union_paix_et_démocratie)
  No wikidata: Nation Unité et Développpement (nation_unité_et_développpement)

```

### CODE REVIEW

**Comment by ondenman** [comment]
Fifteen of the 'Added' have received new upstream IDs. I have mapped them to their existing UUIDs.

**Comment by tmtmtmtm** [comment]
@ondenman are you still working on this?

**Comment by ondenman** [comment]
Closing as it looks like this PR is out of date. There have been subsequent merges for this legislature: 
https://github.com/everypolitician/everypolitician-data/pull/19047
https://github.com/everypolitician/everypolitician-data/pull/22228

**Comment by tmtmtmtm** [comment]
Neither of those merges included the `morph/data.csv` file, though, and trying a build with that file refreshed shows that the issue still remains. You might want to restart this from fresh though…

**Comment by ondenman** [comment]
Issue: https://github.com/everypolitician/everypolitician-data/pull/18879

**Pull request closed without merging**
