### PR TITLE
Nauru: Add new Term

### PR DESCRIPTION
**Pull request by tmtmtmtm**
Source: http://www.naurugov.nr/government-information-office/ (thanks @wfdd)

Scraper: https://morph.io/everypolitician-scrapers/nauru-2016-results

Closes https://github.com/everypolitician/everypolitician-data/issues/13831

### CODE REVIEW

**Comment by wfdd** [comment]
Are those numbers actually votes?  Even with preferential voting (what do they use, STV?), I don't see how there can be more votes than people.

**Comment by wfdd** [comment]
Err, what I meant to say is each candidate couldn't have received more votes than there are people.

**Comment by wfdd** [comment]
Oh the dot you're stripping off on line 56 of the scraper is the decimal mark - I suppose you thought it was the thousands delimiter?  According to the all-knowing Wikipedia, they divide the vote by candidate's rank on the ballot.

**Comment by tmtmtmtm** [comment]
Thanks, fixed (though we don't actually use it anywhere)

**Pull request merged**
