### PR TITLE
Peru (Congreso): Add Twitter list scraper to sources

### PR DESCRIPTION
**Pull request by octopusinvitro**
Scraper is here: [https://morph.io/everypolitician-scrapers/twitter-list-peru-congreso](https://morph.io/everypolitician-scrapers/twitter-list-peru-congreso)

@tmtmtmtm

### CODE REVIEW

**Comment by octopusinvitro** [comment]
I deleted the entries marked as "NO" from the `sources/reconciliation/twitter.csv`:

**23c1bf3e-62e8-4c41-b004-1645c489c4fe has these IDs:**

304765693 https://twitter.com/Wilder_R_Loayza NO
602962505 https://twitter.com/Wilder_Ruiz NO
1580527039 https://twitter.com/wilderruizlo YES

The last one seems to be the one that is active

**77e4c464-f28f-499e-8d97-cdf758d2625c has these IDs:**

1371040064 https://twitter.com/dabugattas16  ?
2949688977 https://twitter.com/abugattasteoye ?

Not clear, so deleted both entries in reconciliation/twitter.csv

**f7440021-ab9a-4291-8d73-a76310fb2789 has these IDs:**

2313823602 https://twitter.com/RosaMavilaLeon YES
1430828804 https://twitter.com/MavilaMesaParla NO

First one seems to be the one that is active

**f935bb3d-a2b1-408a-be2a-bb39e4338125 has these IDs:**

286967608 https://twitter.com/WalterAcha NO
2805238895 https://twitter.com/walterachaperu YES

The last one seems to be the one that is active

**0c1beb9c-d984-4929-9448-1d88c91d73ac has these IDs:**

242807989 https://twitter.com/jaimedelgadoz NO
372426824 https://twitter.com/jrdelgadoz YES

The last one seems to be the one that is active

**68d5eba2-24d2-40c4-b5f3-c66262e369a6 has these IDs:**

4441804276 https://twitter.com/Rodriguez22E NO
2851187889 https://twitter.com/eliasnrodriguez YES

The last one seems to be the one that is active

**Comment by tmtmtmtm** [comment]
Looks great! I think it's safe to add both records for Daniel Abugattás — they're both active, and both clearly him. If we _really_ only wanted to include a single one, `@abugattasteoye` seems the better choice, as the description of `@dabugattas16` directs people to use the former one, but including both seems valid to me.

**Comment by octopusinvitro** [comment]
I added both accounts as you told me, and discovered that the second *also* redirects to the first one! Seems like he uses them for different purposes, where `@dabugattas16` seems to be his personal account while `@abugattasteoye` is a "web platform" for him to interact directly with "his people".

**Comment by tmtmtmtm** [comment]
:+1:

**Pull request merged**
