### PR TITLE
Solomon Islands: Initial data

### PR DESCRIPTION
**Pull request by tmtmtmtm**
part of #141

### CODE REVIEW

**Comment by tmtmtmtm** [comment]
@chrismytton : any idea why this hasn't triggered a parallel PR on viewer-sinatra?

**Comment by chrismytton** [comment]
@tmtmtmtm Looks like the last 2 webhook deliveries timed out for some reason.

screen shot 2015-07-23 at 10 22 25

(that's the one for labeling the pull request, but the opened one timed out as well)

I've redelivered the webhook and it seems to have worked now so I guess it was a transient issue.

**Comment by chrismytton** [comment]
Hmm, it now seems that the deployment job is failing with the following error:

```
Errno::ETIMEDOUT: Connection timed out - connect(2) for "api.github.com" port 443
```

So there seems to be some connectivity issues between Heroku's EU region and GitHub at the moment. The job has been queued for a retry so should Just Work once connectivity is fixed. I can manually retry it in a few hours if that's not the case.

**Comment by chrismytton** [comment]
Ah, as soon as I posted that it finished successfully!

**Comment by tmtmtmtm** [comment]
yep, all seems to be working now. Thanks!

**Pull request merged**
