### PR TITLE
Brunei

### LINKED ISSUE #635: Brunei
* http://majlis-mesyuarat.gov.bn/JMM%20Site%20Pages/Profil%20Ahli-Ahli%20Majlis%20Mesyuarat%20Negara.aspx
* https://en.wikipedia.org/wiki/Legislative_Council_of_Brunei

### PR DESCRIPTION
**Pull request by chrismytton**
Scraper here https://morph.io/chrismytton/brunei-legislative-council

Fixes #635

### CODE REVIEW

**Comment by tmtmtmtm** [comment]
I think the term should really be called "11th Legislative Council" rather than just "Term 11"

**Comment by tmtmtmtm** [comment]
The bottom 9 on the source page are all District Representatives — their district is on their individual pages. Would be good to grab that too.

I think we can also safely leave off the first "line" of the name field, the "Yang Berhormat " or "Yang Amat Mulia"

**Comment by chrismytton** [comment]
@tmtmtmtm I've made those changes now and updated the data in a new commit.

**Comment by tmtmtmtm** [comment]
Looks good! :+1:

**Pull request merged**
