### PR TITLE
Slovakia (National Council): refresh data

### PR DESCRIPTION
**Pull request by everypoliticianbot**
Automated data refresh for Slovakia - National Council

#### Output

```
⤈ No ORDER BY for sources/morph/data.csv
⤈ No ORDER BY for sources/morph/terms.csv
Wikidata renamings:
	Q24877697
Add memberships from sources/morph/data.csv
Merging with sources/morph/wikidata.csv
* 14 of 353 unmatched
	{:id=>"Q3190144", :name=>"Juraj Miškov"}
	{:id=>"Q3059549", :name=>"Eugen Jurzyca"}
	{:id=>"Q1969354", :name=>"Peter Dvorský"}
	{:id=>"Q3506785", :name=>"Ivan Hudec"}
	{:id=>"Q3492711", :name=>"Jozef Kalman"}
	{:id=>"Q12027472", :name=>"Ján Sitek"}
	{:id=>"Q12027101", :name=>"Jozef Zlocha"}
	{:id=>"Q11764466", :name=>"László Sólymos"}
	{:id=>"Q12762300", :name=>"Andrej Hrnčiar"}
	{:id=>"Q602437", :name=>"Daniel Krajcer"}

Data Mismatches
  ☁ Mismatch in birth_date for 4a44a9b9-60b5-486d-be6c-0fab09bd0a88 (2000-07-29) vs 1945-07-29 (for Q12044736)
  ☁ Mismatch in birth_date for 875d02ec-03f1-4437-9812-76dfda70e27a (2000-09-11) vs 1952-09-11 (for Q4597444)

Adding GenderBalance results from sources/gender-balance/results.csv
  ⚥ data for 0; 0 added

Creating 5 term files

Top identifiers:
  526 x nrsr
  526 x parldata
  339 x wikidata
  86 x viaf
  65 x freebase

Creating names.csv
Creating unstable/positions.csv
  Unknown position (x1): Q10956132 Q10956132 — e.g. Q6850543
  Unknown position (x1): Q30185 mayor — e.g. Q6850543
  Unknown position (x1): Q212071 rector — e.g. Q13449869
  Unknown position (x1): Q121998 ambassador — e.g. Q907488
Persons matched to Wikidata: 339 ✓ | 187 ✘
  No wikidata: Ľubomír Petrák (7b9293d8-5b7a-4ada-9f12-160160bb6b55)
  No wikidata: Peter Dubravay (74ecc131-af29-40a0-9946-77c87ac9ffc8)
  No wikidata: Anton Bobrík (07a57c5b-c22a-4aa3-a8b9-c74a0261a53b)
  No wikidata: Peter Šuca (0dd83f67-1ea9-4f74-b901-1654bc946b3e)
  No wikidata: Kamil Krnáč (82bca488-5624-47e1-abad-9e492de90706)
  No wikidata: Beata Sániová (f9bb1f45-f3fa-41be-ae3c-c1d2e6e26159)
  No wikidata: Oľga Keltošová (1b61bf2d-c89b-4a83-98a6-586860e0a5c4)
  No wikidata: Stanislav Fořt (6669ba55-ccef-4472-b258-c63018272d2f)
  No wikidata: Viera Mazúrová (34207a87-9c85-4033-931a-5d89cf5c5f88)
  No wikidata: Viliam Oberhauser (c5f4546e-ef64-4a02-9f4e-beef6d57cda7)
Parties matched to Wikidata: 33 ✓ | 1 ✘
  No wikidata: Klub SOP-LDÚ-SZS (6)

```

### CODE REVIEW

**Comment by ondenman** [comment]
Fixing in: https://github.com/everypolitician/everypolitician-data/pull/17211

**Comment by ondenman** [comment]
Reopening as simpler to fix here.

**Comment by ondenman** [comment]
Member's wikidata ID had changed and wikidata URL was redirecting.

b0dd8311-bc3f-4d6a-8d1b-41158aea706d: Q24877697 → none

Paired new wikidata ID with existing UUID in wikidata reconciliation file.

Fixes: #17206

**Comment by tmtmtmtm** [comment]
Yay. Thanks @ondenman

**Pull request merged**
