### PR TITLE
Cyprus (House of Representatives): refresh data

### PR DESCRIPTION
**Pull request by everypoliticianbot**
Automated data refresh for Cyprus - House of Representatives

#### Output

```
Regenerating sources/morph/data.csv
Regenerating sources/morph/wikidata.csv
Regenerating sources/wikidata/groups.json
Regenerating sources/morph/terms.csv
Regenerating sources/gender-balance/results.csv
  Match incoming name__en to name
Can't match row to existing data: {:id=>"Q12872352", :name__el=>"Άριστος Δαμιανού", :name=>"Άριστος Δαμιανού", :wikipedia__el=>"Άριστος Δαμιανού", :gender=>"male", :original_wikiname=>"Άριστος Δαμιανού", :identifier__wikidata=>"Q12872352"}
Can't match row to existing data: {:id=>"Q12873768", :name__el=>"Αντρέας Καυκαλιάς", :name=>"Αντρέας Καυκαλιάς", :wikipedia__el=>"Αντρέας Καυκαλιάς", :gender=>"male", :birth_date=>"1971-10-21", :original_wikiname=>"Αντρέας Καυκαλιάς", :identifier__wikidata=>"Q12873768"}
Can't match row to existing data: {:id=>"Q12873769", :name__el=>"Αντρέας Φακοντής", :name=>"Αντρέας Φακοντής", :wikipedia__el=>"Αντρέας Φακοντής", :gender=>"male", :birth_date=>"1964-10-22", :original_wikiname=>"Αντρέας Φακοντής", :identifier__wikidata=>"Q12873769"}
Can't match row to existing data: {:id=>"Q12875278", :name__el=>"Γιαννάκης Γαβριήλ", :name=>"Γιαννάκης Γαβριήλ", :wikipedia__el=>"Γιαννάκης Γαβριήλ", :gender=>"male", :birth_date=>"1961-07-17", :original_wikiname=>"Γιαννάκης Γαβριήλ", :identifier__wikidata=>"Q12875278"}
Can't match row to existing data: {:id=>"Q12875354", :name__el=>"Γιώργος Λουκαΐδης", :name=>"Γιώργος Λουκαΐδης", :wikipedia__el=>"Γιώργος Λουκαΐδης", :gender=>"male", :original_wikiname=>"Γιώργος Λουκαΐδης", :identifier__wikidata=>"Q12875354"}
Can't match row to existing data: {:id=>"Q12875947", :name__pl=>"Dimitris Siluris", :name__el=>"Δημήτρης Συλλούρης", :name=>"Δημήτρης Συλλούρης", :wikipedia__el=>"Δημήτρης Συλλούρης", :wikipedia__pl=>"Dimitris Siluris", :gender=>"male", :birth_date=>"1953-07-27", :original_wikiname=>"Δημήτρης Συλλούρης", :given_name=>"Dimitris", :identifier__wikidata=>"Q12875947"}
Can't match row to existing data: {:id=>"Q12876791", :name__el=>"Ειρήνη Χαραλαμπίδου", :name=>"Ειρήνη Χαραλαμπίδου", :wikipedia__el=>"Ειρήνη Χαραλαμπίδου", :gender=>"female", :original_wikiname=>"Ειρήνη Χαραλαμπίδου", :identifier__wikidata=>"Q12876791"}
Can't match row to existing data: {:id=>"Q12879928", :name__el=>"Κώστας Κώστα", :name=>"Κώστας Κώστα", :wikipedia__el=>"Κώστας Κώστα", :gender=>"male", :original_wikiname=>"Κώστας Κώστα", :identifier__wikidata=>"Q12879928"}
Can't match row to existing data: {:id=>"Q12882663", :name__el=>"Πανίκκος Σταυριανός", :name=>"Πανίκκος Σταυριανός", :wikipedia__el=>"Πανίκκος Σταυριανός", :gender=>"male", :birth_date=>"1964-02-07", :original_wikiname=>"Πανίκκος Σταυριανός", :identifier__wikidata=>"Q12882663"}
Can't match row to existing data: {:id=>"Q12884190", :name__el=>"Ρούλα Μαυρονικόλα", :name=>"Ρούλα Μαυρονικόλα", :wikipedia__el=>"Ρούλα Μαυρονικόλα", :gender=>"female", :birth_date=>"1957-07-16", :original_wikiname=>"Ρούλα Μαυρονικόλα", :identifier__wikidata=>"Q12884190"}
Can't match row to existing data: {:id=>"Q12884514", :name__el=>"Σκεύη Κουκουμά Κούτρα", :name=>"Σκεύη Κουκουμά Κούτρα", :wikipedia__el=>"Σκεύη Κουκουμά Κούτρα", :gender=>"female", :birth_date=>"1954-07-18", :original_wikiname=>"Σκεύη Κουκουμά Κούτρα", :identifier__wikidata=>"Q12884514"}
Can't match row to existing data: {:id=>"Q12886195", :name__el=>"Χριστάκης Τζιοβάνης", :name=>"Χριστάκης Τζιοβάνης", :wikipedia__el=>"Χριστάκης Τζιοβάνης", :gender=>"male", :birth_date=>"1956-12-29", :original_wikiname=>"Χριστάκης Τζιοβάνης", :identifier__wikidata=>"Q12886195"}
Can't match row to existing data: {:id=>"Q15950881", :name__pl=>"Stawros Ewagoru", :name__el=>"Σταύρος Ευαγόρου", :name=>"Σταύρος Ευαγόρου", :wikipedia__el=>"Σταύρος Ευαγόρου", :wikipedia__pl=>"Stawros Ewagoru", :gender=>"male", :birth_date=>"1959-12-23", :original_wikiname=>"Σταύρος Ευαγόρου", :identifier__wikidata=>"Q15950881"}
Can't match row to existing data: {:id=>"Q16329024", :name__el=>"Στέλλα Δημητρίου Μισιαούλη", :name=>"Στέλλα Δημητρίου Μισιαούλη", :wikipedia__el=>"Στέλλα Δημητρίου Μισιαούλη", :birth_date=>"1954-10-18", :original_wikiname=>"Στέλλα Δημητρίου Μισιαούλη", :identifier__wikidata=>"Q16329024"}
Can't match row to existing data: {:id=>"Q16329147", :name__el=>"Γιάννος Λαμάρης", :name=>"Γιάννος Λαμάρης", :wikipedia__el=>"Γιάννος Λαμάρης", :gender=>"male", :birth_date=>"1955", :original_wikiname=>"Γιάννος Λαμάρης", :identifier__wikidata=>"Q16329147"}
Can't match row to existing data: {:id=>"Q16329183", :name__el=>"Γιώργος Γεωργίου", :name=>"Γιώργος Γεωργίου", :wikipedia__el=>"Γιώργος Γεωργίου (βουλευτής)", :gender=>"male", :original_wikiname=>"Γιώργος Γεωργίου (βουλευτής)", :identifier__wikidata=>"Q16329183"}
Can't match row to existing data: {:id=>"Q16332700", :name__el=>"Χρίστος Μέσης", :name=>"Χρίστος Μέσης", :wikipedia__el=>"Χρίστος Μέσης", :birth_date=>"1957-08-25", :original_wikiname=>"Χρίστος Μέσης", :identifier__wikidata=>"Q16332700"}
Creating term-2011.csv
Creating names.csv
Wikidata Persons: 12 ✓ | 51 ✘
  Missing: Kosta Kostas
  Missing: Kafkalias Antreas
  Missing: Georgiou Georgios
  Missing: Fyttis Sofoklis
  Missing: Kyriakidou Stella
  Missing: Prokopiou Georgios
  Missing: Champoullas Evgenios
  Missing: Varnava Giorgos
  Missing: Syllouris Dimitris
  Missing: Mitsopoulos Tasos
Wikidata Parties: 4 ✓ | 3 ✘
  Missing: AKEL – Left – New Forces (akel-nd)
  Missing: Cyprus Green Party (oikologoi)
  Missing: Independent (_IND)
Add memberships from sources/morph/data.csv
Merging with sources/morph/wikidata.csv
* 17 of 29 unmatched
⚥ 0

```

### CODE REVIEW

**Comment by wfdd** [comment]
@tmtmtmtm: @ee381b7 is slightly problematic in that it maps the parliament group to the party.

**Comment by tmtmtmtm** [comment]
@wfdd — do you mean just in the case of AKEL-ND, or for the other groups as well? In general I've found that Wikidata doesn't do a good job of differentiating these in many countries, but if there are better entries there to point to, I'm happy to switch the IDs (or patches very welcome against https://github.com/everypolitician/everypolitician-data/blob/master/data/Cyprus/House_of_Representatives/sources/manual/group_wikidata.csv !) 

I'm also happy to create pages on Wikidata for concepts that are missing — though that generally requires me to understand the concept a little better than I do here, and I couldn't find anything on parliament.cy that explained the set-up (in English, anyway).  Any pointers or explanations you can give might help!

Thanks for catching this.

**Comment by wfdd** [comment]
AKEL is the only party forming an 'alliance'[1] and go by a different name in elections and in parliament; but I don't think there's any provision for alliances in law or in the House procedures.  According to Art 73 of the [Constitution](http://www.presidency.gov.cy/presidency/presidency.nsf/all/1003AEDD83EED9C7C225756F0023C6AD/$file/CY_Constitution.pdf),

> Any political party which is represented at least by twelve per centum of the total number of the Representatives in the House of Representatives can form and shall be entitled to be recognised as a political party group.

Committee membership is split relative to the groups' seats in parliament, [allegedly](http://www.parliament.cy/easyconsole.cfm/id/144):

> Οι πολιτικές κομματικές ομάδες στη Βουλή εκπροσωπούνται δεόντως σε κάθε κοινοβουλευτική επιτροπή.

For administrative purposes, it seems likely that AKEL-ND would be regarded as a distinct party.

[1]: This would be AKEL plus non-CC members, plus independent leftists, though not often in national elections.

**Comment by tmtmtmtm** [comment]
Thanks @wfdd — I've created a new Wikidata entry for the Group (https://www.wikidata.org/wiki/Q22808995), and pointed at it instead. Does that look like a sensible approach?

**Comment by wfdd** [comment]
Yep, that seems reasonable.  Shame about the translations, but I'm also quite unhappy about how they're extracted from Wikipedia article titles.  Wikipedia follows a 'common name' policy, whereby articles are named after commonly-used names; for instance, in the cases of Finnish and Telugu (assuming `tl` is Telugu - I've not bothered to look it up ;), the name was abbreviated to 'AKEL'.

**Comment by tmtmtmtm** [comment]
Great. Feel free to change the Wikidata ones by the way — they were all simply seeded from Wikipedia article titles so that there'd be _something_ there. You know the context better, so feel free to make the data better :)

**Comment by wfdd** [comment]
Ya, I didn't mean to suggest it's your fault; I was quibbling about Wikidata.

**Pull request merged**
