### PR TITLE
Added data.parliament.scot data source for Scottish Parliament data

### PR DESCRIPTION
**Pull request by mashedkeyboard**
This adds data from data.parliament.scot for Scottish Parliament members.

I've had a go at adding support for this myself, but without any documentation it's a slightly blind attempt. It works, but I can't work out how to get it to reconcile Mairi Gougeon, James Douglas-Hamilton, George Foulkes, Ken Macintosh, Liz Smith and Sir David Steel correctly between the sources.

Log is as below:

```
17:20:07 [0;32;49mValidating CSVs[0m
17:20:08 [0;32;49mAdding memberships from sources/parlparse/data.csv[0m
	⚠ Missing area UUID mapping
17:20:08 [0;32;49mMerging with sources/morph/wikidata.csv[0m
17:20:08 [0;32;49mMerging with sources/morph/scotparl.csv[0m
Cannot apply correction: {:identifier__scotparl=>"2108", :field=>"name", :old=>"Ken Macintosh", :new=>"Kenneth Macintosh"}
Cannot apply correction: {:identifier__scotparl=>"4014", :field=>"name", :old=>"Liz Smith", :new=>"Elizabeth Smith"}
Cannot apply correction: {:identifier__scotparl=>"2263", :field=>"name", :old=>"Sir David Steel", :new=>"Lord Steel of Aikwood"}
Cannot apply correction: {:identifier__scotparl=>"2108", :field=>"name", :old=>"Ken Macintosh", :new=>"Kenneth Macintosh"}
Cannot apply correction: {:identifier__scotparl=>"4014", :field=>"name", :old=>"Liz Smith", :new=>"Elizabeth Smith"}
Cannot apply correction: {:identifier__scotparl=>"2263", :field=>"name", :old=>"Sir David Steel", :new=>"Lord Steel of Aikwood"}
Cannot apply correction: {:identifier__scotparl=>"2108", :field=>"name", :old=>"Ken Macintosh", :new=>"Kenneth Macintosh"}
Cannot apply correction: {:identifier__scotparl=>"4014", :field=>"name", :old=>"Liz Smith", :new=>"Elizabeth Smith"}
Cannot apply correction: {:identifier__scotparl=>"2263", :field=>"name", :old=>"Sir David Steel", :new=>"Lord Steel of Aikwood"}
[This repeats hundreds of times, so I've cut out the identical logging here]
[0;35;49m	* 3 of 305 unmatched[0m
	{:name=>"Mairi Gougeon"}
	{:name=>"George Foulkes"}
	{:name=>"James Douglas-Hamilton"}
17:20:08 [0;32;49mAdding unmigrated GenderBalance results from sources/gender-balance/results.csv[0m
[0;36;49m  ⚥ data for 623; 0 added[0m
17:20:08 [0;32;49mGenerating legacy_id file[0m
17:20:08 [0;32;49mVerifying sources/merged.csv[0m
17:20:08 [0;32;49mConverting to Popolo[0m
17:20:08 [0;32;49mAdding term information[0m
17:20:08 [0;32;49mAdding area information[0m
17:20:09 [0;32;49mAdding election information[0m
17:20:09 [0;32;49mAdding party information[0m
17:20:09 [0;32;49mCreating termfiles[0m
17:20:09 [0;32;49mCreating names.csv[0m
17:20:09 [0;32;49mCreating unstable/positions.csv[0m
  ☇ No dates for Stewart Maxwell (Q1710696) as Minister for Housing and Welfare
  ☇ No dates for Keith Brown (Q1738042) as Minister for Transport and Veterans
------------------------------------------------------------------------
Persons matched to Wikidata: 305 ✓ 
Areas matched to Wikidata: 123 ✓ 
Parties matched to Wikidata: 9 ✓ | 1 ✘
  No wikidata: None (none)
Terms matched to Wikidata: 5 ✓ 
```

### CODE REVIEW

**Comment by tmtmtmtm** [comment]
Hi @mashedkeyboard — thanks for this! I'm travelling at the moment, so can't look closely at this until later next week, but if you're wanting to dig any deeper yourself in the meantime, I think the main thing you'll want is a reconciliation file, rather than a 'corrections' one — it'll tie together the IDs in your new source with the UUIDs we've given them. Alternatively if the IDs from this source could be added to Wikidata, then we could combine the sources automatically.

I suspect also that with the current setup, you'd probably also want to have this as the second source in the `instructions.json` file — i.e. above the Wikidata source, rather than after it: that way the images from this source will take priority, and you wouldn't need to 'ignore' the ones from Wikidata.

Apologies that this is all so undocumented!

**Comment by mashedkeyboard** [comment]
Thanks @tmtmtmtm - working out the reconciliation file was exactly what I was trying to do! I can't see how you generate it though for all the ones it does auto-match - I assume it _is_ generated, right?

**Comment by tmtmtmtm** [comment]
There are a variety of tools that you could use to do the reconciliation: all that matters is that you create a file in the correct format linking the IDs. If you're already comfortable with something like [OpenRefine](http://openrefine.org/), you could use that, but we also have one that's (sort of) built-in. With the `instructions.json` you have, you would trigger that by running `GENERATE_RECONCILIATION_INTERFACE=scotparl bundle exec rake clean default`

That will create a local single-page HTML file you can open in a browser, and step through each person, comparing the best guess matches for each, ordered by how confident it is. You should be able to race through most of those selecting the first match each time, unless there are any cases where multiple members have the same, or very similar, names. Then you can take the csv file it generates (which will automatically appear at the end, or any time you hit `ESC`), and paste it to the file you've specified for reconciliation (presumably `sources/reconciliation/scotparl.csv`)

Again, the documentation is pretty much non-existent here, so if you get stuck, I'm happy to do this part myself some time next week, or talk you through whatever I've forgotten to explain here!

**Comment by mashedkeyboard** [comment]
Brilliant, that works great! All done and updated :) Thanks very much!

**Comment by tmtmtmtm** [comment]
@mashedkeyboard that's fantastic, thanks! Would you be able to squash faa6c9bf and 485db7a together (so we lose the "corrections" detour entirely from the history), and then rebase them over the current `master`? The easiest way to do that might actually be to commit the changes to the human-edited files separately (i.e. `sources/instructions.json` and `sources/reconciliation/scotparl.csv`), discard the rebuilt files, rebase over master, and then do a `bundle exec rake clean default` and commit the resulting changes separately. (It's probably also easiest for you to just drop the changes to `countries.json` entirely: I'll rebuild that separately after merging this to avoid any potential conflicts.)

Or, if there's any problem with any of that, I could also do it myself by cherry-picking your changes across to a new branch, editing them (but keeping you as the author), and constructing a new PR from it.

**Comment by mashedkeyboard** [comment]
Done, thanks! I've not updated countries.json as per request :)

**Comment by mashedkeyboard** [comment]
Awesome, all done! :)

**Pull request merged**
