### PR TITLE
Slovakia National Council: Add 2016 term

### PR DESCRIPTION
**Pull request by ondenman**
Adds new term from new scraper source.

The latest term has not been added to the source from which the previous terms have been scraped. As such, a new scraper is required. This PR adds the new scraper.

screen shot 2016-11-02 at 12 12 03

screen shot 2016-11-02 at 12 15 13

Sanity check
------------

* [x] election has happened and new term is not in EveryPolitician already
* [x] you're looking at the *correct* house for *correct* country
* [x] there's not a much more urgent legislature you could be doing, is there?

New term (ep-data)
------------------

* [x] a single `terms.csv` exists and has previous terms *and* this new term in it
* [x] previous term end date is correct, and source credited in commit message
* [x] new term start date is correct, and source credited in commit message

New data (ep-data)
------------------

* [x] new memberships are merged or reconciled
* [x] party groupings are correct (screenshot)

Reconciliations against other sources
------------------------------------

* [x] wikidata is being reconciled (or else an issue exists for it) (Wikidata will be reconciled in a later commit. See issue: https://github.com/everypolitician/everypolitician-data/issues/19644)

Pull request
------------

* [x] has country: legislature name in title
* [x] has screenshot of staged PR-site (especially "party groupings")
* [x] Travis tests pass
* [x] is assigned to reviewer

### CODE REVIEW

**Comment by tmtmtmtm** [comment]
@oliver: from a clean build I'm getting a lot of warning about missing party data:

```
Parties matched to Wikidata: 33 ✓ | 9 ✘
  No wikidata: Klub SOP-LDÚ-SZS (6)
  No wikidata: Kotleba - Ľudová strana Naše Slovensko (party/kotleba_-_Ľudová_strana_naše_slovensko)
  No wikidata: OBYČAJNÍ ĽUDIA a nezávislé osobnosti (OĽANO-NOVA) (party/obyČajnÍ_Ľudia_a_nezávislé_osobnosti_(oĽano-nova))
  No wikidata: SMER – sociálna demokracia (party/smer_–_sociálna_demokracia)
  No wikidata: Slovenská národná strana (party/slovenská_národná_strana)
```

looks like you forgot to regenerate `sources/wikidata/groups.json` after reconciling the groups to Wikidata IDs.

**Comment by tmtmtmtm** [comment]
@ondenman You've left the 'Reconciliations against other sources' section out of this. In particular, these new people aren't yet reconciled against Wikidata (largely as the scraper for that still hasn't been updated.) It's OK to do that in a new PR, you still need to include that in the description, with that box left unchecked, and a link to the Issue you've created to remind us that we still need to do this.

**Comment by ondenman** [comment]
@tmtmtmtm I've added an issue and updated the checklist.

**Comment by tmtmtmtm** [comment]
Woot! 👍  🚀

**Pull request merged**
