### PR TITLE
Mongolia (State Great Khural): refresh data

### PR DESCRIPTION
**Pull request by everypoliticianbot**
Automated data refresh for Mongolia - State Great Khural

#### Output

```
⤈ No ORDER BY for sources/morph/data.csv
Add memberships from sources/morph/data.csv
Merging with sources/morph/official.csv
* 48 of 119 unmatched
	{:id=>"380", :name=>"Khavdislam Badyelkhan"}
	{:id=>"416", :name=>"Damdin Tsogtbaatar"}
	{:id=>"402", :name=>"Navaan-Yunden Oyundari"}
	{:id=>"387", :name=>"Jambal Ganbaatar"}
	{:id=>"419", :name=>"Lkhagvaa Eldev-Ochir"}
	{:id=>"391", :name=>"Dorjdamba Damba-Ochir"}
	{:id=>"376", :name=>"Namsrai Amarzaya"}
	{:id=>"406", :name=>"Shatarbal Radnaased"}
	{:id=>"393", :name=>"Bold Javkhlan"}
	{:id=>"405", :name=>"Bukhchuluun Purevdorj"}
Merging with sources/morph/wikidata.csv
* 14 of 47 unmatched
	{:id=>"Q24174853", :name=>"Нямаагийн Энхболд"}
	{:id=>"Q25848773", :name=>"Жаргалтулгын Эрдэнэбат"}
	{:id=>"Q24174855", :name=>"Агипарын Бакей"}
	{:id=>"Q7849825", :name=>"Tsogtyn Batbayar"}
	{:id=>"Q24174854", :name=>"Данзангийн Лүндээжанцан"}
	{:id=>"Q24174856", :name=>"Раднаасүмбэрэлийн Гончигдорж"}
	{:id=>"Q24174857", :name=>"Мигэддоржийн Батчимэг"}
	{:id=>"Q276238", :name=>"Санжаасүрэнгийн Оюун"}
	{:id=>"Q7070853", :name=>"Nyamjavyn Batbayar"}
	{:id=>"Q23771599", :name=>"Nyamaagiin Enkhbold"}
Adding GenderBalance results from sources/gender-balance/results.csv
  ⚥ data for 0; 0 added

Creating 2 term files

Top identifiers:
  33 x wikidata
  8 x freebase
  6 x viaf
  1 x lcauth

Creating names.csv
Creating unstable/positions.csv
Persons matched to Wikidata: 33 ✓ | 84 ✘
  No wikidata: Sanjaasürengiin Oyuun (9be31e26-dc52-465f-9d00-2aa4fd3b187e)
  No wikidata: Yangugiin Sodbaatar (b823623f-91a6-427a-95da-ea3d771e589c)
  No wikidata: Shinensambuugiin Saikhansambuu (fcedf776-8306-4e2e-be00-40383fca81aa)
  No wikidata: Logiin Tsog (7063f26d-b1af-4049-a98b-582bbe340e05)
  No wikidata: Tsedeviin Dashdorj (b95eab1d-6326-4ea8-8014-980c6f74583b)
  No wikidata: Garidkhüügiin Bayarsaikhan (621f0e59-e228-455b-b7c8-539a3103645b)
  No wikidata: Khayangaagiin Bolorchuluun (70e525ac-89aa-4951-a711-630fab059ca6)
  No wikidata: Saldangiin Odontuyaa (52f7528b-97cf-446a-a656-0db19916d06c)
  No wikidata: Püreviin Altangerel (993e645f-d077-4e5d-af9b-473d6b1ed386)
  No wikidata: Dendeviin Terbishdagva (9398cdb6-d8de-45f4-9e84-ff1c65616c44)
Parties matched to Wikidata: 5 ✓ 

```

### CODE REVIEW

**Comment by tmtmtmtm** [comment]
Party groupings look correct:

screen shot 2016-09-19 at 20 59 23

**Comment by ondenman** [comment]
Members now scraped with constituencies:
screen shot 2016-09-29 at 11 17 19

**Comment by tmtmtmtm** [comment]
@ondenman there's something slightly odd going on here, that I don't really have time to dig deeper into right now, as I'm off today. The bot was reporting that all the new people have non-UUID ids, so I rebased over master in case this was related to the bug we had recently around this. But after doing that, the UUIDs were clean (though strangely reporting no diffs locally), but all the area information is still missing. It's possible that something I've done here has clobbered your changes somehow, so you should be careful about brining mine down over the top of yours.

**Comment by ondenman** [comment]
Closing in favour of https://github.com/everypolitician/everypolitician-data/pull/19077

**Pull request closed without merging**
