### PR TITLE
Twitter list Croatia

### PR DESCRIPTION
**Pull request by ondenman**
Add twitter data from https://twitter.com/electionista/lists/hr
via scraper at https://morph.io/everypolitician-scrapers/twitter-list-croatia

### CODE REVIEW

**Comment by tmtmtmtm** [comment]
@ondenman you seem to have broken `countries.json` quite badly here

**Comment by tmtmtmtm** [comment]
@ondenman Looks good, though I'm curious why you accepted https://twitter.com/DarkoMilinovic and not https://twitter.com/Darko_Milinovic ?

**Comment by ondenman** [comment]
@tmtmtmtm  Replaced https://twitter.com/DarkoMilinovic with https://twitter.com/Darko_Milinovic. Account has more posts and followers.

**Comment by tmtmtmtm** [comment]
@ondenman 👍 , but it would be good to give https://github.com/everypolitician/everypolitician-data/pull/14356/commits/66126c03dbfb6a77ee27a44f4b6a45a8b1e64b3a a more descriptive commit message to explain what you're actually doing.

**Pull request merged**
