### PR TITLE
Lebanon (Parliament): refresh data

### PR DESCRIPTION
**Pull request by everypoliticianbot**
Automated data refresh for Lebanon - Parliament

#### Output

```
⤈ No ORDER BY for sources/morph/wikipedia.csv
⤈ No ORDER BY for sources/morph/wikidata.csv
Wikidata renamings:
	Q19668129
Add memberships from sources/morph/wikipedia.csv
Merging with sources/morph/wikidata.csv
* 20 of 92 unmatched
	{:id=>"Q16119754", :name=>"سليم سلهب"}
	{:id=>"Q12252104", :name=>"يوسف خليل"}
	{:id=>"Q2915518", :name=>"Suleiman Frangieh"}
	{:id=>"Q12229362", :name=>"غازي يوسف"}
	{:id=>"Q20409433", :name=>"عاطف مجدلاني"}
	{:id=>"Q20392616", :name=>"إبراهيم كنعان"}
	{:id=>"Q16122381", :name=>"نبيل نقولا"}
	{:id=>"Q20423212", :name=>"محمد قباني"}
	{:id=>"Q2429767", :name=>"Ali La Pointe"}
	{:id=>"Q16123722", :name=>"عمار حوري"}
Adding GenderBalance results from sources/gender-balance/results.csv
  ⚥ data for 0; 0 added

Creating 1 term file

Top identifiers:
  72 x wikidata
  40 x freebase
  11 x viaf
  4 x munzinger
  4 x sudoc

Creating names.csv
Creating unstable/positions.csv
  Unknown position (x1): Q25820215 Minister of Culture — e.g. Q3514836
Persons matched to Wikidata: 72 ✓ | 57 ✘
  No wikidata: Atef Majdalani (288b5d95-c164-4e25-8c11-aab912aaa67f)
  No wikidata: Simon Abi Ramia (fe1be621-6217-4b46-8cd2-7f1590de779a)
  No wikidata: Khodr Habib (41305331-34e1-40dd-8960-9c17f20d510a)
  No wikidata: Nabil Nicolas (b44927e1-88c5-4fc6-9f48-78106019399a)
  No wikidata: Bassem Chabb (61ea8170-b2e9-45b3-ab0e-e8eaf4b3f5a5)
  No wikidata: Mouiine el Merehbi (ec51700b-5595-4134-aefa-f0073eed0b2b)
  No wikidata: Abbas Hachem (580665a2-a37d-486d-b6a4-e2c801a0656b)
  No wikidata: Shant Chinchinian (Jinjinian) (df0e5213-c9ef-4ea7-81a8-3f3594fc3758)
  No wikidata: Tony Abou Khater (0c492515-7c93-418e-b14d-bf784a6c52d0)
  No wikidata: Elie Aoun (c11fcfef-3715-4624-92d6-07137ec704ef)
Parties matched to Wikidata: 19 ✓ | 11 ✘
  No wikidata: Kataeb and Zahle Block (party/kataeb_and_zahle_block)
  No wikidata: Safadi Bloc (party/safadi_bloc)
  No wikidata: Lebanon first and Zahle Bloc (party/lebanon_first_and_zahle_bloc)
  No wikidata: Zahle In our Hearts Bloc (party/zahle_in_our_hearts_bloc)
  No wikidata: Independent within March 14 (party/independent_within_march_14)

```

### CODE REVIEW

**Comment by tmtmtmtm** [comment]
still broken #14067

**Comment by octopusinvitro** [comment]
@tmtmtmtm I think we solved the wrong UUID assignments and they now appear under name changes with the right UUIDs

**Comment by tmtmtmtm** [comment]
@octopusinvitro and Suleiman Frangieh _should_ be disappearing?

What about the wikidata that's going missing for Ibrahim Najjar (Q3147509)?

**Comment by octopusinvitro** [comment]
@tmtmtmtm Suleiman with id `ddf6` was removed by us and [given back his real id `ed00`](https://github.com/everypolitician/everypolitician-data/pull/15255/commits/9b3bb7b739b86185e353fdc840e9aed2b9fc9eeb). That [seems to have added the right data back to the relevant files](https://github.com/everypolitician/everypolitician-data/pull/15255/commits/80d6c1e4df983f662341cc528428b1b7159feb61). He also appears in the section "Name changes".

Regarding Ibrahim with id `c54e`, he seemed to be disappearing from the data so we added him in a memberships file, which [seems to have put him back in the data](https://github.com/everypolitician/everypolitician-data/pull/15255/commits/fdce56c6e88f5665d466cce7ada53bef16ebe56e). He appears under "Wikidata changes" as `c54e6db7-0f4c-4073-afd9-79809724b184`: Q3147509 → none, so I don't understand what happens [here](https://github.com/everypolitician/everypolitician-data/pull/15374/files#diff-1).

Regarding PR #15374, it seems to have the same problems that this one suffered at the beginning before we worked on the import.

**Comment by tmtmtmtm** [comment]
#15374 is just an another automated build — we'll get one of these every day. Usually those close any pre-existing PRs for that country, but because you've added commits to this one, it keeps it open and pings you instead.

The Wikidata for Ibrahim Najjar is disappearing because there is no longer any entry for "Q3147509" in `sources/morph/wikidata.csv`. You'll need to find out why the Wikidata scraper no longer finds that person.

**Comment by tmtmtmtm** [comment]
LGTM

**Pull request merged**
