### PR TITLE
Czech Republic (Chamber of Deputies): refresh data

### PR DESCRIPTION
**Pull request by everypoliticianbot**
Automated data refresh for Czech Republic - Chamber of Deputies

#### Output

```
⤈ No ORDER BY for sources/morph/data.csv
FIXME: Unhandled 'quantity': {:amount=>"+11372", :unit=>"1", :upperBound=>"+11373", :lowerBound=>"+11371"}
Add memberships from sources/morph/data.csv
Merging with sources/morph/wikidata.csv
Data Mismatches
  ☁ Mismatch in birth_date for 09e86212-c35f-4800-a8c1-c36d80f0d7c0 (1955-01-01) vs 1942-03-01 (for Q10854110)
  ☁ Mismatch in birth_date for 21373dd2-5fcd-405c-b24e-2106c0932bc6 (1933-06-25) vs 1933-06-02 (for Q12026480)
  ☁ Mismatch in birth_date for 6e0cfb1d-959f-4230-9040-b77c32358a74 (1946-11-14) vs 1946-10-14 (for Q12028649)
  ☁ Mismatch in birth_date for cf371a17-ceca-4a87-9bca-45a22aea656f (1900-01-01) vs 1970-09-01 (for Q14704946)
  ☁ Mismatch in birth_date for 04b4713c-8c05-45c8-a334-2b418817e206 (1963-03-20) vs 1963-03-30 (for Q159490)
  ☁ Mismatch in death_date for db4898dc-e61c-48f8-89da-2d0157f0e31d (2015-04-15) vs 2015-04-16 (for Q348896)
  ☁ Mismatch in birth_date for 903467af-a11c-4d67-83c4-b30540a72fa1 (1946-04-28) vs 1946-05-28 (for Q447452)
  ☁ Mismatch in death_date for 121b1adf-0ad8-4678-9679-e20078a4f699 (1999-11-22) vs 1999-11-21 (for Q4561809)
* 1 of 744 unmatched
	{:id=>"Q12059170", :name=>"Tomáš Bergman"}
Adding GenderBalance results from sources/gender-balance/results.csv
  ⚥ data for 0; 0 added


Top identifiers:
  893 x parldata
  893 x psp
  743 x wikidata
  308 x viaf
  79 x nkc

Creating names.csv
Creating unstable/positions.csv
  Unknown position (x1): Q7614320 finance minister — e.g. Q10819807
  Unknown position (x1): Q12053193 List of Ministers of Transport of the Czech Republic — e.g. Q983583
  Unknown position (x1): Q12052827 List of Ministers of Health of the Czech Republic — e.g. Q983583
  Unknown position (x1): Q26197430 Q26197430 — e.g. Q12035364
  Unknown position (x1): Q83307 minister — e.g. Q707590
  Unknown position (x1): Q1162163 director — e.g. Q3377548
  Unknown position (x1): Q12047080 vice-dean — e.g. Q3377548
  Unknown position (x1): Q723682 dean — e.g. Q3377548
  Unknown position (x1): Q212071 rector — e.g. Q3377548
  Unknown position (x1): Q2113250 Prorector — e.g. Q3377548
  Unknown position (x1): Q1055894 deputy — e.g. Q348896
  Unknown position (x2): Q26197353 Q26197353 — e.g. Q12019440
  Unknown position (x2): Q30185 mayor — e.g. Q712430
  Unknown position (x5): Q140686 chairperson — e.g. Q3377548
Persons matched to Wikidata: 743 ✓ | 150 ✘
  No wikidata: František Novosad (48e750d2-e1a9-40ec-b6ce-aaedf51838c7)
  No wikidata: Jan Navrátil (5af0ad5e-8081-4210-a2de-7acc06f996d5)
  No wikidata: Viktor Paggio (367f55dd-f55a-4d98-aa7e-d388fecb814f)
  No wikidata: Jan Vidím (6ec411e8-236f-45af-b9af-3c4d175afe8e)
  No wikidata: Čestmír Hofhanzl (991f8317-46e0-430f-b19b-8dc186dd3d47)
  No wikidata: Jaromír Schling (eb4f0880-303c-4607-bcc9-7a49f162b7d9)
  No wikidata: Tomáš Kvapil (8dd40a52-a644-46f8-b7ea-c8b7c93a7db8)
  No wikidata: Zbyněk Stanjura (8307a589-19cf-451c-9241-88692c637fd4)
  No wikidata: Vít Bárta (0fe753ee-ee51-475c-9b0f-88fe4192e373)
  No wikidata: Markéta Wernerová (c37145c2-297a-41d3-98b7-c560b8d50663)
Parties matched to Wikidata: 57 ✓ | 1 ✘
  No wikidata: Nezařazení - Strana zelených (754)

```

### CODE REVIEW

**Comment by ondenman** [comment]
Looks transient. Scraper was timing out. Updated scraper, removing batch processing.

**Comment by ondenman** [comment]
Reopening. Need to update instructions file. Will also refresh data in this PR.

**Comment by ondenman** [comment]
Wikidata IDs were being lost as scraper was failing. Updated wikidata scraper -- removing batch processing which was likely cause. Refreshed data.

Moved scraper. @tmtmtmtm https://morph.io/tmtmtmtm/czech-chamber-of-deputies-wikidata can be removed.

**Comment by tmtmtmtm** [comment]
@ondenman how did you generate the countries.json in this? The sha [it's pointing at](https://github.com/everypolitician/everypolitician-data/pull/18231/commits/8c4746dcea817c429e2bc7ddce775c4fc33d6ef4) for everything doesn't exist!

@chrismytton I think we need some sort of travis check to catch cases like this. Any suggestions?

**Pull request merged**
