### PR TITLE
Hong Kong: Wikidata ids for terms

### PR DESCRIPTION
**Pull request by marfi**
Better

### CODE REVIEW

**Comment by tmtmtmtm** [comment]
Thanks @marfi — these changes are great, and are what we've been doing in lots of legislatures anyway, but can I ask that you also change the column name from `source` to `wikidata` when you do this? Then when we rebuild the data (which you can do with a `bundle exec rake clean default`) that will also flow through into the final Popolo file as well.

I'm happy to do that myself if you prefer, though you'll need to give me permission on the Pull Requests: https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/

**Comment by marfi** [comment]
@tmtmtmtm I have the box: "Allow edits from maintainers." checked. I think you already can edit them? I have nothing against you doing it, ofc. :)

**Comment by tmtmtmtm** [comment]
Summary of changes in `data/Hong_Kong/Legislative_Council/ep-popolo-v1.0.json`:

## People

### Added


No people added


### Removed


No people removed


### Name Changes


No name changes


### Additional Name Changes


No name changes


### Wikidata Changes


No changes


## Organizations

### Added


No organizations added


### Removed


No organizations removed


## Memberships

### Added

No memberships added


### Removed

No memberships removed

**Comment by tmtmtmtm** [comment]
Excellent, thanks. Rebuilt and merged! (I also added a bunch more info about all the terms to Wikidata)

**Pull request merged**
