### PR TITLE
[WIP] Ukraine

### LINKED ISSUE #111: Ukraine
http://w1.c1.rada.gov.ua/pls/site2/p_deputat_list

includes 7 previous convocations, back to 1990

### PR DESCRIPTION
**Pull request by henare**
This is a work in progress to add the Ukrainian parliament.

The data generation runs OK but I haven't committed it yet because there's a bunch of outstanding questions I have about the data in the scraper repo: https://github.com/openaustralia/ukraine_verkhovna_rada_deputies

Eventually... resolves #111.

### CODE REVIEW

**Comment by tmtmtmtm** [comment]
Thanks @henare — this is looking great. Sorry for the mess-up on the docs of how to set up the Rakefiles — I rushed through the change to that so that it would be much quicker for _me_ to add all the new countries this week for the GLOW push, and didn't get time to bring the docs up to date. And as it's almost always me that adds this part even when someone else has written the scraper, I foolishly didn't think it was quite as urgent to do that!

Do you plan to backfill previous terms at some point, or will you only be working with the current deputies? (It's certainly not essential for EP, though we'd like to add the historic ones too at some point — I'm just curious, as I could imagine it being useful in a TheyVoteForYou context)

**Comment by henare** [comment]
>Thanks @henare — this is looking great. Sorry for the mess-up on the docs of how to set up the Rakefiles — I rushed through the change to that so that it would be much quicker for me to add all the new countries this week for the GLOW push, and didn't get time to bring the docs up to date. And as it's almost always me that adds this part even when someone else has written the scraper, I foolishly didn't think it was quite as urgent to do that!

Not a problem. I figured I was one of the first people other than you that had added stuff so I was going to help improve the documentation :)

>Do you plan to backfill previous terms at some point, or will you only be working with the current deputies? (It's certainly not essential for EP, though we'd like to add the historic ones too at some point — I'm just curious, as I could imagine it being useful in a TheyVoteForYou context)

I'll only add the current deputies in this PR but adding the historical stuff to the scraper looks pretty simple (the pages look the same at least).

**Comment by tmtmtmtm** [comment]
I fixed up the start date for the term (to 2014, rather than 2015), and explicitly set the party of non-aligned members to Позафракційні (Yay for an SQL-based API making that [trivial](Позафракційні)), and put this live. Future changes to the underlying data should be picked up semi-regularly (it's not automated yet, but I rebuild by hand semi-frequently. Yell if you make any changes you want me to rebuild — the more often you make me do that, the more likely I am to automate it more! :))

**Comment by henare** [comment]
>I fixed up the start date for the term (to 2014, rather than 2015)

Duh, silly me - thanks for picking this up.

>and explicitly set the party of non-aligned members to Позафракційні (Yay for an SQL-based API making that trivial)

I'd be happy to have this in the scraper data itself if it would be better.

> and put this live.

Woohoo, thanks for all your help getting this live Tony!

**Pull request merged**
