### PR TITLE
Ghana (Parliament): refresh data from local scraper

### PR DESCRIPTION
**Pull request by ondenman**
The scraper failed on Morph and hasn't yet run since the most
recent update.

Rather than waiting for it to re-run, I have run the scraper locally.

### CODE REVIEW

**Comment by ondenman** [comment]
screen shot 2017-01-04 at 15 23 03

**Comment by tmtmtmtm** [comment]
> It appears that constituency information for these members has changed.

Are you convinced that it has actually changed correctly, or might there be an error in the scraper?

**Comment by ondenman** [comment]
screen shot 2017-01-06 at 10 25 45


screen shot 2017-01-06 at 10 23 24

screen shot 2017-01-06 at 10 25 10

**Comment by ondenman** [comment]
§

**Pull request merged**
