### PR TITLE
Cyprus (House of Representatives): refresh data

### PR DESCRIPTION
**Pull request by everypoliticianbot**
Automated data refresh for Cyprus - House of Representatives

#### Output

```
Add memberships from sources/morph/openpatata.csv
Merging with sources/morph/wikidata.csv
Adding GenderBalance results from sources/gender-balance/results.csv
  ⚥ data for 0; 0 added

Creating 2 term files

Top identifiers:
  92 x openpatata
  63 x parliament_cy
  33 x wikidata
  3 x europarlmep
  3 x freebase

Creating names.csv
Creating unstable/positions.csv
Persons matched to Wikidata: 33 ✓ | 59 ✘
  No wikidata: Mousiouttas Marinos (fc1fb71c-641f-4787-8d78-0df0c9d6c69a)
  No wikidata: Pittokopitis Charalampos (a9cf199a-9d95-4bf9-96d4-b3862ba8c6cb)
  No wikidata: Kyriakou Maria (b220307f-2f9d-48c6-b120-6247bfe8e719)
  No wikidata: Chatzigiannis Kyriakos (031e1ad7-2f4a-41d9-89b6-640b675702fa)
  No wikidata: Misos Aristotelis (fb4260b7-1c75-41df-8cee-079fbb9c3c21)
  No wikidata: Georgiadis Charis (3e6eb062-3610-4544-8841-8b98de796671)
  No wikidata: Kyprianou Andreas (c6dd8909-ab61-4f2d-8417-7030dbb66ee7)
  No wikidata: Zachariou Zacharias (db57ba63-8af0-45c3-9fa9-0687f96ed33a)
  No wikidata: Stavrou Eleni (1300a45f-e959-4c03-86ea-0e617453d75a)
  No wikidata: Christos Christou (6a241356-b6d8-42b4-9e39-1e4d28c7966c)
Parties matched to Wikidata: 5 ✓ | 6 ✘
  No wikidata: Citizens’ Alliance (sypol)
  No wikidata: National Popular Front (elam)
  No wikidata: Cyprus Green Party (oikologoi)
  No wikidata: Cyprus Greens – Citizens Cooperation (oikologoi-sp)
  No wikidata: Solidarity Movement (allilengyi)

```

### CODE REVIEW

**Comment by wfdd** [comment]
Christos Christou was renamed to Christou Christos in openpatata.  It doesn't look like the reconciler has picked this up.

**Comment by tmtmtmtm** [comment]
@wfdd thanks for the heads up. If it had just been a _name_ change, we'd have handled it fine; but we don't automatically pick up on ID changes — those need to be handled manually (as it's much better to have two records for one person than one record for two people wrongly combined).

**Comment by wfdd** [comment]
@tmtmtmtm, it looks like this removed the new id - the right order is `christou-christos`. Sorry for the confusion.

**Comment by wfdd** [comment]
@tmtmtmtm, this still needs fixing.

**Comment by tmtmtmtm** [comment]
I don't think there's anything to do at this end. The previous change mapped both IDs from the scraper to the same UUID here, which is the correct behaviour AIUI. But because the scraper is additive it's ended up with a row for both IDs. EP then correctly de-dupes those, but the earlier ID "wins" in terms of flowing through. 

So I think this is just a matter of emptying all the data from the scraper and rerunning it, which I've done, but there's a bit of a backlog atm. When that finally makes it way through, I'm fairly confident that this will all Just Work™.

**Comment by wfdd** [comment]
cool, looks like that's fixed it, thanks.

**Pull request merged**
