### PR TITLE
Ukraine (Verkhovna Rada): refresh official

### PR DESCRIPTION
**Pull request by everypoliticianbot**
Automated refresh of official for Ukraine - Verkhovna Rada

#### Output

```
Switched to a new branch 'ukraine-verkhovna-rada-1499093415'
Add memberships from sources/morph/official.csv
20287 -> 92e2a548-3b35-4dfd-acb5-8a9778791c6d
Merging with sources/morph/wikidata.csv
Merging with sources/morph/genderbalance.csv

Top identifiers:
  461 x rada
  460 x wikidata
  138 x verkhovna_rada
  52 x freebase
  33 x viaf

Creating names.csv
Persons matched to Wikidata: 460 ✓ | 1 ✘
  No wikidata: Буглак Юрій Олександрович (92e2a548-3b35-4dfd-acb5-8a9778791c6d)
Parties matched to Wikidata: 10 ✓ | 1 ✘
  No wikidata: Група "Відродження" (2795)
Areas matched to Wikidata: 0 ✓ | 199 ✘
[ukraine-verkhovna-rada-1499093415 2db6404] Ukraine: Refresh from upstream changes
 6 files changed, 669 insertions(+), 731 deletions(-)

```

### CODE REVIEW

**Comment by tmtmtmtm** [comment]
@ondenman can you check if these look sensible and make sure there's nothing going missing? (You don't have to actually verify the data: we can trust the upstream source — just make sure that there are no memberships completely vanishing rather than being replaced by ones with new dates, etc.) Thanks!

**Comment by ondenman** [comment]
The data has multiple membership in a single term for individual members. The membership changes are being caused by date changes.

Several disappearing memberships have dates that fall within the dates of another membership.

## Overlapping memberships

### Барна Олег Степанович

```diff
18062,Барна Олег Степанович,Олег,Степанович,Барна,Тернопільська область,8,2016-01-26,2016-03-29,http://static.rada.gov.ua/dep_img8/d167_1.jpg,,http://itd.rada.gov.ua/mps/info/page/18062,Позафракційні,,167,18062
- 18062,Барна Олег Степанович,Олег,Степанович,Барна,Тернопільська область,8,2016-01-27,2016-03-28,http://static.rada.gov.ua/dep_img8/d167_1.jpg,,http://itd.rada.gov.ua/mps/info/page/18062,Позафракційні,,167,18062
```

### Кишкар Павло Миколайович

```diff
18006,Кишкар Павло Миколайович,Павло,Миколайович,Кишкар,Загальнодержавному багатомандатному округу,8,2015-09-02,2016-03-31,http://static.rada.gov.ua/dep_img8/sp7.jpg,"Політична партія ""Об'єднання ""САМОПОМІЧ""",http://itd.rada.gov.ua/mps/info/page/18006,Позафракційні,,,18006
- 18006,Кишкар Павло Миколайович,Павло,Миколайович,Кишкар,Загальнодержавному багатомандатному округу,8,2015-09-03,2016-03-30,http://static.rada.gov.ua/dep_img8/sp7.jpg,"Політична партія ""Об'єднання ""САМОПОМІЧ""",http://itd.rada.gov.ua/mps/info/page/18006,Позафракційні,,,18006
```

### Кривенко Віктор Миколайович

```diff
айович,Віктор,Миколайович,Кривенко,Загальнодержавному багатомандатному округу,8,2015-09-02,2016-03-31,http://static.rada.gov.ua/dep_img8/sp5.jpg,"Політична партія ""Об'єднання ""САМОПОМІЧ""",http://itd.rada.gov.ua/mps/info/page/18005,Позафракційні,,,18005
- 18005,Кривенко Віктор Миколайович,Віктор,Миколайович,Кривенко,Загальнодержавному багатомандатному округу,8,2015-09-03,2016-03-30,http://static.rada.gov.ua/dep_img8/sp5.jpg,"Політична партія ""Об'єднання ""САМОПОМІЧ""",http://itd.rada.gov.ua/mps/info/page/18005,Позафракційні,,,18005
```

### Негой Федір Федорович

```diff
15823,Негой Федір Федорович,Федір,Федорович,Негой,Херсонська область,8,2015-04-24,2016-04-14,http://static.rada.gov.ua/dep_img8/d186_1.jpg,,http://itd.rada.gov.ua/mps/info/page/15823,Позафракційні,,186,15823
- 15823,Негой Федір Федорович,Федір,Федорович,Негой,Херсонська область,8,2015-04-25,2016-04-13,http://static.rada.gov.ua/dep_img8/d186_1.jpg,,http://itd.rada.gov.ua/mps/info/page/15823,Позафракційні,,186,15823
```

### Развадовський Віктор Йосипович

```diff
2308,Развадовський Віктор Йосипович,Віктор,Йосипович,Развадовський,Житомирська область,8,2016-12-06,2017-02-24,http://static.rada.gov.ua/dep_img8/d67_1.jpg,,http://itd.rada.gov.ua/mps/info/page/2308,Позафракційні,,67,2308
- 2308,Развадовський Віктор Йосипович,Віктор,Йосипович,Развадовський,Житомирська область,8,2016-12-07,2017-02-23,http://static.rada.gov.ua/dep_img8/d67_1.jpg,,http://itd.rada.gov.ua/mps/info/page/2308,Позафракційні,,67,2308
```

### Суслова Ірина Миколаївна

```diff
11999,Суслова Ірина Миколаївна,Ірина,Миколаївна,Суслова,Загальнодержавному багатомандатному округу,8,2015-02-11,2016-03-30,http://static.rada.gov.ua/dep_img8/sp6.jpg,"Політична партія ""Об'єднання ""САМОПОМІЧ""",http://itd.rada.gov.ua/mps/info/page/11999,Позафракційні,,,11999
- 11999,Суслова Ірина Миколаївна,Ірина,Миколаївна,Суслова,Загальнодержавному багатомандатному округу,8,2015-02-12,2016-03-29,http://static.rada.gov.ua/dep_img8/sp6.jpg,"Політична партія ""Об'єднання ""САМОПОМІЧ""",http://itd.rada.gov.ua/mps/info/page/11999,Позафракційні,,,11999
```

### Томенко Микола Володимирович

```diff
5415,Томенко Микола Володимирович,Микола,Володимирович,Томенко,Загальнодержавному багатомандатному округу,8,2014-11-27,2016-02-02,http://static.rada.gov.ua/dep_img8/bp8.jpg,"ПАРТІЯ ""БЛОК ПЕТРА ПОРОШЕНКА""",http://itd.rada.gov.ua/mps/info/page/5415,"Фракція ПАРТІЇ ""БЛОК ПЕТРА ПОРОШЕНКА""",2613,,5415
- 5415,Томенко Микола Володимирович,Микола,Володимирович,Томенко,Загальнодержавному багатомандатному округу,8,2016-02-03,2016-03-25,http://static.rada.gov.ua/dep_img8/bp8.jpg,"ПАРТІЯ ""БЛОК ПЕТРА ПОРОШЕНКА""",http://itd.rada.gov.ua/mps/info/page/5415,Позафракційні,,,5415
```

### Шаповалов Юрій Анатолійович

```diff
15803,Шаповалов Юрій Анатолійович,Юрій,Анатолійович,Шаповалов,Полтавська область,8,2016-11-04,2017-02-24,http://static.rada.gov.ua/dep_img8/d146_1.jpg,,http://itd.rada.gov.ua/mps/info/page/15803,Позафракційні,,146,15803
- 15803,Шаповалов Юрій Анатолійович,Юрій,Анатолійович,Шаповалов,Полтавська область,8,2016-11-05,2017-02-23,http://static.rada.gov.ua/dep_img8/d146_1.jpg,,http://itd.rada.gov.ua/mps/info/page/15803,Позафракційні,,146,15803
```

## Losing incorrect dates

Матківський Богдан Миронович is losing a membership with incorrect dates. Start and end dates are reversed.

```diff
- 18119,Матківський Богдан Миронович,Богдан,Миронович,Матківський,Львівська область,8,2015-11-27,2015-10-09,http://static.rada.gov.ua/dep_img8/d121_1.jpg,,http://itd.rada.gov.ua/mps/info/page/18119,"Фракція ПАРТІЇ ""БЛОК ПЕТРА ПОРОШЕНКА""",2613,121,18119
```

## No end date

Вітко Артем Леонідович. The first membership has no end date.

```diff
18043,Вітко Артем Леонідович,Артем,Леонідович,Вітко,Загальнодержавному багатомандатному округу,8,2014-11-27,,http://static.rada.gov.ua/dep_img8/rp7.jpg,Радикальна Партія Олега Ляшка,http://itd.rada.gov.ua/mps/info/page/18043,Фракція Радикальної партії Олега Ляшка,2615,,18043
- 18043,Вітко Артем Леонідович,Артем,Леонідович,Вітко,Загальнодержавному багатомандатному округу,8,2016-03-18,,http://static.rada.gov.ua/dep_img8/rp7.jpg,Радикальна Партія Олега Ляшка,http://itd.rada.gov.ua/mps/info/page/18043,Позафракційні,,,18043
```

**Comment by ondenman** [comment]
As much as I can tell, all the membership changes are solely down to changes in dates.

**Comment by tmtmtmtm** [comment]
@ondenman are you saying that it's safe to merge this, because we're not actually losing information and/or this data is more correct than what is live? Or are these changes in dates potentially problematic?

**Comment by ondenman** [comment]
@tmtmtmtm With the exception of two, the disappearing memberships are duplicates with differing dates. Example:

screen shot 2017-07-05 at 12 35 33

Вітко Артем Леонідович and Томенко Микола Володимирович look problematic. 

According to the live data, Вітко Артем Леонідович became 'non-factional' in 2016 but the incoming data loses this.

screen shot 2017-07-05 at 12 36 47

The same goes for Томенко Микола Володимирович

screen shot 2017-07-05 at 12 42 01

**Pull request closed without merging**
