### PR TITLE
South Korea (National Assembly): Add term 20 from popong data

### PR DESCRIPTION
**Pull request by chrismytton**
This adds the new term 20 data from this scraper: https://morph.io/everypolitician-scrapers/korea-popong-data. I've reconciled against the existing data for term 19.

Fixes https://github.com/everypolitician/everypolitician-data/issues/14151

# Notes to merger

After this has been merged https://morph.io/tmtmtmtm/korea-popong-data can be deleted if desired because we're now using https://morph.io/everypolitician-scrapers/korea-popong-data.

### CODE REVIEW

**Comment by chrismytton** [comment]
@tmtmtmtm 👀

**Comment by chrismytton** [comment]
> Though you've forgotten to rebuild countries.json…

Blast! Forgot @everypoliticianbot doesn't do that any more…done in https://github.com/everypolitician/everypolitician-data/pull/18445/commits/d7ea0ee842e911ba1e382889411420a306d5cdb6.

> Are you going to also take care of getting Wikidata for the new people (probably as part of another PR), or should someone else look into that?

I will have a crack at that, I'll open a ticket now.

**Comment by tmtmtmtm** [comment]
screen shot 2016-10-11 at 16 36 21

**Comment by tmtmtmtm** [comment]
vs Wikipedia:

screen shot 2016-10-11 at 16 37 04

**Pull request merged**
