### PR TITLE
Cabo Verde (Assembleia Nacional): refresh data

### PR DESCRIPTION
**Pull request by everypoliticianbot**
Automated data refresh for Cabo Verde - Assembleia Nacional

#### Output

```
Add memberships from sources/morph/data.csv
Adding GenderBalance results from sources/gender-balance/results.csv
  ⚥ data for 0; 0 added

Creating 2 term files
Creating names.csv
Persons matched to Wikidata: 0 ✓ | 144 ✘
Parties matched to Wikidata: 3 ✓ 

```

### CODE REVIEW

**Comment by tmtmtmtm** [comment]
@wfdd getting closer…

**Comment by wfdd** [comment]
@tmtmtmtm: The four that were removed don't appear to be listed on the [site](http://www.parlamento.cv/deputados2.aspx) under the 8th term.  Try typing 'Felisberto' in the name field, select the 8th legislature and click on 'Pesquisar'.

**Comment by tmtmtmtm** [comment]
They definitely were there before though (or we wouldn't have them). See also http://www.dgape.cv/images/pdf/Deputados_Eleitos.pdf

I suspect we'll have to copy their entries from the old `data.csv` into a manual membership file, then.

**Comment by wfdd** [comment]
Okay, that still leaves us with having separate UUIDs for everybody who was re-elected.

**Comment by tmtmtmtm** [comment]
> Okay, that still leaves us with having separate UUIDs for everybody who was re-elected.

For that the easiest way is to pull each term in separately and reconcile them, which I've now done. How does that all look?

**Comment by wfdd** [comment]
Looks good to me 👍

**Comment by tmtmtmtm** [comment]
Yay!

**Pull request merged**
