### PR TITLE
Greenland (Inatsisartut): refresh all sources

### PR DESCRIPTION
**Pull request by everypoliticianbot**
Automated refresh of all sources for Greenland - Inatsisartut

#### Output

```
Switched to a new branch 'greenland-inatsisartut-1499143397'
Add memberships from sources/morph/official.csv
laura_táunâjik -> 0c9476b6-5f6a-4bc7-9e14-55f2b10aec38
Merging with sources/morph/wikidata.csv
Data Mismatches
* 15 of 44 unmatched
	{:id=>"Q12328916", :name=>"Niels Thomsen"}
	{:id=>"Q381139", :name=>"Jonathan Motzfeldt"}
	{:id=>"Q6044767", :name=>"Mikael Petersen"}
	{:id=>"Q1794743", :name=>"Augusta Salling"}
	{:id=>"Q2046855", :name=>"Thue Christiansen"}
	{:id=>"Q11257352", :name=>"Hans-Pavia Rosing"}
	{:id=>"Q19787806", :name=>"Knud Kristiansen"}
	{:id=>"Q4974123", :name=>"Henriette Rasmussen"}
	{:id=>"Q2196317", :name=>"Asii Chemnitz Narup"}
	{:id=>"Q4569194", :name=>"Mikael Gam"}
Adding GenderBalance results from sources/gender-balance/results.csv
  ⚥ data for 316; 221 added


Top identifiers:
  29 x wikidata
  8 x freebase
  2 x viaf
  2 x google_knowledge
  1 x isni

Creating names.csv
Persons matched to Wikidata: 29 ✓ | 131 ✘
  No wikidata: Asii Chemnitz Narup (719c3a68-7124-488d-a9b9-6ca484feca1d)
  No wikidata: Sofus Joelsen (61c1d713-33a3-45df-a5f8-a0493d0d0507)
  No wikidata: Laura Táunâjik (0c9476b6-5f6a-4bc7-9e14-55f2b10aec38)
  No wikidata: Niels Màtâk´ (cd355ee0-f47a-49cb-8921-4dc4bea3f36e)
  No wikidata: Peter G. Samuelsen (1c277514-c550-4975-a729-015ab6fb392b)
  No wikidata: Isak Davidsen (d9329257-43da-4d93-8140-565e5cc96be0)
  No wikidata: Naimanngitsoq Petersen (d62bcbe2-50e4-43f3-a4d5-35f759b609c1)
  No wikidata: Holger Sivertsen (fc62020a-40a7-4bb7-8532-7d28b56ee5fd)
  No wikidata: Per Rosing-Petersen (2f830c08-28cf-4cad-9097-cb92234a2485)
  No wikidata: Lars Mathæussen (231b19af-3c8b-4679-b068-08f90b46fd43)
Parties matched to Wikidata: 13 ✓ | 1 ✘
  No wikidata: Kandidatforbund (kandidatforbund)
Areas matched to Wikidata: 0 ✓ 
[greenland-inatsisartut-1499143397 139b135] Greenland: Refresh from upstream changes
 19 files changed, 206 insertions(+), 224 deletions(-)

```

### CODE REVIEW

**Comment by wfdd** [comment]
## People

### Added

- [x] Laura Táunâjik - corrected spelling of Laura Tàunâjik, needs reconciling

### Removed

- [x] Laura Tàunâjik - apparent misspelling of Laura Táunâjik (note the accent)
- [x] Hans Pvia Rosing - misspelled dupe of Hans Pavia Rosing

## Memberships

### Added

#### term/12

- [x] Jens-Erik Kirkegaard (2017-04-24 - ) - reappointed
- [x] Kalistat Lund ( - 2017-04-23) - left office
- [x] Laura Táunâjik - see Memberships above

### Removed

#### term/10

- [x] Akitsinnguaq Olsen - dupe though listed as belonging to a different party

#### term/12

- [x] Kalistat Lund - left office
- [x] Laura Tàunâjik - see Memberships above

#### term/2

- [x] Hans Pvia Rosing - see Memberships above

#### term/4

- [ ] **Jonathan Motzfeldt - can't explain, possibly removed/listed in error?**

#### term/8

- [ ] **Agathe Fontain - can't explain, possibly removed/listed in error?**
- [ ] **Hans Enoksen - can't explain, possibly removed/listed in error?**

#### term/9

- [ ] **Olga P. Berthelsen - can't explain, possibly removed/listed in error?**

**Comment by wfdd** [comment]
@tmtmtmtm noticed this one's been bouncing around for a while and occasionally tagged with 'broken import', so I thought I'd try to explain the little that I can.

**Comment by tmtmtmtm** [comment]
Thanks @wfdd — this one has been on my list to explore at some point, but as you've seen it's never quite high enough priority. The ones that you have as "can't explain, possibly removed/listed in error" are the ones that worry me, as if they're removed in error, we certainly don't want to also remove them here, but if they were originally an error that has now been corrected upstream, then we definitely do! Any suggestions for other ways of checking them?

**Comment by wfdd** [comment]
I'm quite certain at least 2 of them were removed in error: Motzfelt and Eroksen, both being PM in term 4 and 8, respectively (http://www.ina.gl/media/2526862/d-inatsisartut-website-inatsisartutgl-media-28274-valg-til-inatsisartut-da-web.pdf, p. 31ff.).

**Pull request closed without merging**
