### PR TITLE
Dominican Republic (Chamber of Deputies): Add new term

### PR DESCRIPTION
**Pull request by everypoliticianbot**
This PR adds the new 2016 term and moves the 2010 term to the manual sources since it seems to have disappeared from the official sources.

The bot commits have been deleted .

### CODE REVIEW

**Comment by octopusinvitro** [comment]
Closes #16405

**Comment by tmtmtmtm** [comment]
This Pull Request has been superseded by #16748 but there are non-bot commits.

@octopusinvitro is this pull request still needed?

**Comment by tmtmtmtm** [comment]
@octopusinvitro the "Output" section in the description doesn't seem correct — for example the claim "Creating 1 term file" is a little unexpected if it's actually creating 2. Is this an obsolete output from the prior bot-PR you cannibalised?

**Comment by octopusinvitro** [comment]
@tmtmtmtm Yes. It's removed now.

**Comment by tmtmtmtm** [comment]
@octopusinvitro by simply copying the files, rather than moving them, git has lost the history. I'd suggest splitting this into two PRs — the first where you `git mv` the files to 'manual/' and rebuild (to show that there are no changes to output). Then a second PR to add the new term.

**Comment by octopusinvitro** [comment]
Closing this as it was the wrong approach

**Pull request closed without merging**
